# Generated by Django 5.1.1 on 2024-09-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("create", "Создана"),
                    ("launched", "Запущена"),
                    ("completed", "Завершена"),
                ],
                max_length=20,
                verbose_name="Статус рассылки",
            ),
        ),
    ]
